### ISSUE TITLE
Missing target attribute

### ISSUE THREAD

**Issue by ivan-pi** [arjenmarkus/io_utilities#1]
These variables are supposed to have the `target` attribute:

https://github.com/arjenmarkus/io_utilities/blob/8b3a01f7b793457e54b2d37d6e04deca340736ba/test/test_keyvars.f90#L9-L11

The `keyvar(...)` type uses `pointers` internally.

**Comment by arjenmarkus** [comment]
You're absolutely right. I have updated the source and the documentation.
